name: untitled5
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get:
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  file_picker: ^5.3.2
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  image_picker: ^0.8.9
  firebase_database: ^10.2.3
  gcloud: ^0.8.9
  reference: ^0.2.0-beta.4
  modal_progress_hud_nsn: ^0.4.0
  fluttertoast: ^8.2.2
  curved_navigation_bar: ^1.0.3 #latest version
  google_nav_bar: ^5.0.6
  cloud_firestore: ^4.8.2
  flutter_polls: ^0.1.5
  flutter_form_builder: ^9.0.0
  provider: ^6.0.5
  google_maps_flutter: ^2.3.0
  location: ^4.4.0
  shared_preferences: ^2.2.0
  string_validator: ^1.0.0
  email_validator: ^2.1.17
  pay: ^1.1.1
  flutter_webrtc: ^0.9.35
  razorpay_flutter: ^1.3.5
  syncfusion_flutter_calendar: ^22.1.39
  table_calendar: ^3.0.9
  lottie: ^2.6.0
  url_launcher: ^6.1.12
  geolocator: ^10.0.1
  permission_handler: ^10.3.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/
    - fonts/
    - assets/page-1/images/auto-group-g9az.png
    - assets/page-1/images/android-battery.png
    - assets/page-1/images/community-lines-1.png
    - assets/page-1/images/share.png
    - assets/page-1/images/dismiss-button.png
    - assets/page-1/images/snaphelp.png
    - assets/page-1/images/padlock-1.png
    - assets/page-1/images/share-sHB.png
    - assets/page-1/images/bars.png
    - assets/page-1/images/tabler-password-fingerprint.png
    - assets/page-1/images/group.png
    - assets/page-1/images/mdi-linkedin.png
    - assets/page-1/images/share-HWZ.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/line-3.png
    - assets/page-1/images/line-3-Ni5.png
    - assets/page-1/images/community-lines-1-abj.png
    - assets/page-1/images/community-lines-1-2M7.png
    - assets/page-1/images/ellipse-2.png
    - assets/page-1/images/share-U3s.png
    - assets/page-1/images/medimeet-1-DCm.png
    - assets/page-1/images/medimeet-1.png
    - assets/page-1/images/medimeet-1-aHo.png
    - assets/page-1/images/subtract.png
    - assets/page-1/images/medimeet-1-GpZ.png
    - assets/page-1/images/share-aeD.png
    - assets/page-1/images/auto-group-2luz.png
    - assets/page-1/images/subtract-SGy.png
    - assets/page-1/images/line-3-EMo.png
    - assets/page-1/images/community-lines-1-34m.png
    - assets/page-1/images/ellipse-2-CpR.png
    - assets/page-1/images/vector-kKB.png
    - assets/page-1/images/expand-thread.png
    - assets/page-1/images/medimeet-1-oS9.png
    - assets/page-1/images/line-3-xcH.png
    - assets/page-1/images/medimeet-1-uVK.png
    - assets/page-1/images/subtract-EWD.png
    - assets/page-1/images/vector-GoB.png
    - assets/page-1/images/ellipse-18-bg.png
    - assets/page-1/images/android-battery-Gxy.png
    - assets/page-1/images/medimeet.png
    - assets/page-1/images/line-3-DKX.png
    - assets/page-1/images/share-n7j.png
    - assets/page-1/images/ellipse-13-bg.png
    - assets/page-1/images/share-DRK.png
    - assets/page-1/images/line-3-5iR.png
    - assets/page-1/images/auto-group-7czw.png
    - assets/page-1/images/android-battery-tbK.png
    - assets/page-1/images/android-battery-bKw.png
    - assets/page-1/images/community-lines-1-1yK.png
    - assets/page-1/images/expand-thread-3Q5.png
    - assets/page-1/images/formkit-instagram.png
    - assets/page-1/images/medimeet-1-6Eu.png
    - assets/page-1/images/typcn-video-outline.png
    - assets/page-1/images/community.png
    - assets/page-1/images/ellipse-14-bg.png
    - assets/page-1/images/group-chX.png
    - assets/page-1/images/community-KJR.png
    - assets/page-1/images/fa6-brands-square-x-twitter.png
    - assets/page-1/images/share-GwK.png
    - assets/page-1/images/vector-e4h.png
    - assets/page-1/images/medimeet-ysf.png
    - assets/page-1/images/ellipse-17-bg.png
    - assets/page-1/images/snaphelp-Bk5.png
    - assets/page-1/images/expand-thread-Zvy.png
    - assets/page-1/images/medimeet-1-8k1.png
    - assets/page-1/images/ellipse-16-bg.png
    - assets/page-1/images/community-lines-1-SSm.png
    - assets/page-1/images/snaphelp-pHw.png
    - assets/page-1/images/dashicons-admin-site.png
    - assets/page-1/images/subtract-Dmj.png
    - assets/page-1/images/vector-j9j.png
    - assets/page-1/images/solar-posts-carousel-vertical-linear.png
    - assets/page-1/images/vector-AVw.png
    - assets/page-1/images/community-7vy.png
    - assets/page-1/images/ellipse-13-bg-5so.png
    - assets/page-1/images/auto-group-f7rt.png
    - assets/page-1/images/bars-LNM.png
    - assets/page-1/images/expand-thread-gx1.png
    - assets/page-1/images/medimeet-JiV.png
    - assets/page-1/images/community-lines-1-7JR.png
    - assets/page-1/images/community-lines-1-MiZ.png
    - assets/page-1/images/ellipse-16-bg-iZ7.png
    - assets/page-1/images/vector-iCH.png
    - assets/page-1/images/expand-thread-41F.png
    - assets/page-1/images/auto-group-9iem.png
    - assets/page-1/images/rectangle-12.png
    - assets/page-1/images/ellipse-15-bg.png
    - assets/page-1/images/share-d3f.png
    - assets/page-1/images/ellipse-18-bg-VXf.png
    - assets/page-1/images/auto-group-t4am.png
    - assets/page-1/images/ellipse-15-bg-WJm.png
    - assets/page-1/images/ellipse-14-bg-nzM.png
    - assets/page-1/images/ellipse-2-VYV.png
    - assets/page-1/images/solar-phone-calling-rounded-broken.png
    - assets/page-1/images/ellipse-17-bg-6Ks.png
    - assets/page-1/images/bi-threads-fill.png
    - assets/page-1/images/create-menu.png
    - assets/page-1/images/bars-dHj.png
    - assets/page-1/images/ellipse-16-bg-g6D.png
    - assets/page-1/images/medimeet-1Bf.png
    - assets/page-1/images/android-battery-UCy.png
    - assets/page-1/images/share-KLd.png
    - assets/page-1/images/ellipse-14-bg-wNZ.png
    - assets/page-1/images/android-battery-VWR.png
    - assets/page-1/images/auto-group-q3ds.png
    - assets/page-1/images/bars-Xhs.png
    - assets/page-1/images/bars-HNR.png
    - assets/page-1/images/snaphelp-ze5.png
    - assets/page-1/images/medimeet-tGy.png
    - assets/page-1/images/community-lines-1-zEM.png
    - assets/page-1/images/auto-group-thz1.png
    - assets/page-1/images/line-3-mdj.png
    - assets/page-1/images/medimeet-ctH.png
    - assets/page-1/images/snaphelp-tpq.png
    - assets/page-1/images/medimeet-1-1Rb.png
    - assets/page-1/images/share-QtH.png
    - assets/page-1/images/ellipse-15-bg-9uj.png
    - assets/page-1/images/community-TZ3.png
    - assets/page-1/images/android-battery-jiq.png
    - assets/page-1/images/ellipse-19-bg.png
    - assets/page-1/images/line-3-aKB.png
    - assets/page-1/images/ellipse-14-bg-iNm.png
    - assets/page-1/images/line-3-twK.png
    - assets/page-1/images/ellipse-17-bg-FQV.png
    - assets/page-1/images/ellipse-13-bg-bz9.png
    - assets/page-1/images/expand-thread-SvD.png
    - assets/page-1/images/ellipse-13-bg-G5w.png
    - assets/page-1/images/community-dUD.png
    - assets/page-1/images/serenity-app-design-1-1.png
    - assets/page-1/images/vector-DyT.png
    - assets/page-1/images/uim-whatsapp.png
    - assets/page-1/images/figma-image-community-1-1.png
    - assets/page-1/images/expand-thread-WUZ.png
    - assets/page-1/images/share-fL5.png
    - assets/page-1/images/ellipse-19-bg-cMX.png
    - assets/page-1/images/ellipse-18-bg-LYR.png
    - assets/page-1/images/auto-group-urqs.png
    - assets/page-1/images/snaphelp-1.png
    - assets/page-1/images/snaphelp-1-jtD.png
    - assets/page-1/images/snaphelp-1-Ea5.png
    - assets/page-1/images/medimeet-1-Q2d.png
    - assets/page-1/images/figma-image-community-1-2.png
    - assets/page-1/images/ellipse-14-bg-3uK.png
    - assets/page-1/images/snaphelp-1-WGR.png
    - assets/page-1/images/bars-AgH.png
    - assets/page-1/images/snaphelp-1-u9K.png
    - assets/page-1/images/snaphelp-1-ucM.png
    - assets/page-1/images/ellipse-14-bg-8hF.png
    - assets/page-1/images/share-wDB.png
    - assets/page-1/images/community-lines-1-Mbw.png
    - assets/page-1/images/snaphelp-fTX.png
    - assets/page-1/images/share-9L5.png
    - assets/page-1/images/bars-abj.png
    - assets/page-1/images/rectangle-40.png
    - assets/page-1/images/rectangle-38.png
    - assets/page-1/images/expand-thread-rWd.png
    - assets/page-1/images/expand-thread-5w7.png
    - assets/page-1/images/share-SBK.png
    - assets/page-1/images/community-lines-1-yF7.png
    - assets/page-1/images/share-iiM.png
    - assets/page-1/images/ellipse-14-bg-eDf.png
    - assets/page-1/images/medimeet-1-qL5.png
    - assets/page-1/images/line-3-4js.png
    - assets/page-1/images/medimeet-EN5.png
    - assets/page-1/images/auto-group-hrnz.png
    - assets/page-1/images/snaphelp-1-VcV.png
    - assets/page-1/images/snaphelp-QFT.png
    - assets/page-1/images/rectangle-39.png
    - assets/page-1/images/vector-io3.png
    - assets/page-1/images/snaphelp-1-QBs.png
    - assets/page-1/images/snaphelp-1-Rsf.png
    - assets/page-1/images/snaphelp-1-Ky3.png
    - assets/page-1/images/ellipse-19.png
    - assets/page-1/images/snaphelp-1-gRw.png
    - assets/page-1/images/medimeet-1-31b.png
    - assets/page-1/images/community-se9.png
    - assets/page-1/images/snaphelp-1-BdB.png
    - assets/page-1/images/expand-thread-taM.png
    - assets/page-1/images/share-4Wu.png
    - assets/page-1/images/share-Ct1.png
    - assets/page-1/images/expand-thread-5qK.png
    - assets/page-1/images/share-4WD.png
    - assets/page-1/images/expand-thread-1wF.png
    - assets/page-1/images/vector-kx1.png
    - assets/page-1/images/ellipse-14-bg-aZf.png
    - assets/page-1/images/share-WRF.png
    - assets/page-1/images/community-lines-1-ajK.png
    - assets/page-1/images/community-HKf.png
    - assets/page-1/images/group-HGM.png
    - assets/page-1/images/expand-thread-CMP.png
    - assets/page-1/images/snaphelp-fmK.png
    - assets/page-1/images/expand-thread-2th.png
    - assets/page-1/images/share-7oo.png
    - assets/page-1/images/expand-thread-oAq.png
    - assets/page-1/images/group-22.png
    - assets/page-1/images/share-yHs.png
    - assets/page-1/images/bars-hw7.png
    - assets/page-1/images/share-VFF.png
    - assets/page-1/images/medimeet-iBT.png
    - assets/page-1/images/screenshot-2023-10-07-at-511-1-bg.png
    - assets/page-1/images/group-YY9.png
    - assets/page-1/images/share-63s.png
    - assets/page-1/images/vector-fWq.png
    - assets/page-1/images/expand-thread-LUy.png
    - assets/page-1/images/share-Ur5.png
    - assets/page-1/images/snaphelp-S2M.png
    - assets/page-1/images/ellipse-17.png
    - assets/page-1/images/auto-group-roi9.png
    - assets/page-1/images/ellipse-15.png
    - assets/page-1/images/group-nFB.png
    - assets/page-1/images/share-eA5.png
    - assets/page-1/images/share-xTb.png
    - assets/page-1/images/share-dn1.png
    - assets/page-1/images/share-FWh.png
    - assets/page-1/images/share-Tbo.png
    - assets/page-1/images/android-battery-LN5.png
    - assets/page-1/images/rectangle-38-wA9.png
    - assets/page-1/images/share-ri5.png
    - assets/page-1/images/expand-thread-bTF.png
    - assets/page-1/images/vector-qrH.png
    - assets/page-1/images/rectangle-39-yhT.png
    - assets/page-1/images/android-battery-ezV.png
    - assets/page-1/images/expand-thread-1P7.png
    - assets/page-1/images/ellipse-16.png
    - assets/page-1/images/figma-image-community-1-5.png
    - assets/page-1/images/ellipse-13-bg-Ecq.png
    - assets/page-1/images/ellipse-13-bg-TLV.png
    - assets/page-1/images/bars-xNm.png
    - assets/page-1/images/vector-Hqb.png
    - assets/page-1/images/auto-group-q7rr.png
    - assets/page-1/images/vector-uaZ.png
    - assets/page-1/images/expand-thread-5iZ.png
    - assets/page-1/images/vector-YNV.png
    - assets/page-1/images/line-3-Zw7.png
    - assets/page-1/images/share-9LM.png
    - assets/page-1/images/rectangle-38-5jo.png
    - assets/page-1/images/rectangle-40-Bnq.png
    - assets/page-1/images/medimeet-qcV.png
    - assets/page-1/images/figma-image-community-1-3.png
    - assets/page-1/images/vector-jxm.png
    - assets/page-1/images/vector-pPb.png
    - assets/page-1/images/rectangle-39-3XF.png
    - assets/page-1/images/ellipse-18.png
    - assets/page-1/images/group-7GD.png
    - assets/page-1/images/group-g4R.png
    - assets/page-1/images/share-Da9.png
    - assets/page-1/images/expand-thread-7fX.png
    - assets/page-1/images/line-3-fqT.png
    - assets/page-1/images/community-fTw.png
    - assets/page-1/images/group-8F3.png
    - assets/page-1/images/expand-thread-syK.png
    - assets/page-1/images/share-fLm.png
    - assets/page-1/images/vector-zq7.png
    - assets/page-1/images/group-fxV.png
    - assets/page-1/images/figma-image-community-1-4.png
    - assets/page-1/images/vector-rLy.png
    - assets/page-1/images/share-diH.png
    - assets/page-1/images/rectangle-39-gDF.png
    - assets/page-1/images/rectangle-39-Ysb.png
    - assets/page-1/images/android-battery-JZo.png
    - assets/page-1/images/rectangle-40-R1j.png
    - assets/page-1/images/bars-dQd.png
    - assets/page-1/images/medimeet-1-LVF.png
    - assets/page-1/images/ellipse-13-bg-YKj.png
    - assets/page-1/images/community-lines-1-fQM.png
    - assets/page-1/images/snaphelp-1-TVB.png
    - assets/page-1/images/ellipse-13-bg-cAu.png
    - assets/page-1/images/vector-5SR.png
    - assets/page-1/images/vector-XiH.png
    - assets/page-1/images/vector-hG5.png
    - assets/page-1/images/vector-tpH.png
    - assets/page-1/images/rectangle-38-7Jh.png
    - assets/page-1/images/ellipse-13-bg-kZ7.png
    - assets/page-1/images/icon-box.png
    - assets/page-1/images/property-1chevron-left.png
    - assets/page-1/images/vector-3vq.png
    - assets/page-1/images/rectangle-40-mDT.png
    - assets/page-1/images/vector-h77.png
    - assets/page-1/images/figma-image-community-1-2-Tww.png
    - assets/page-1/images/bars-QWM.png
    - assets/page-1/images/property-1chevron-right.png
    - assets/page-1/images/icon-box-jAR.png
    - assets/page-1/images/vector-SyF.png
    - assets/page-1/images/auto-group-t8gy.png
    - assets/page-1/images/android-battery-MaR.png
    - assets/page-1/images/auto-group-mb8d.png
    - assets/page-1/images/android-battery-FzH.png
    - assets/page-1/images/rectangle-38-tVP.png
    - assets/page-1/images/icon-box-1jX.png
    - assets/page-1/images/rectangle-40-VXP.png
    - assets/page-1/images/bars-ULH.png
    - assets/page-1/images/icon-box-gjB.png
    - assets/page-1/images/icon-box-v6M.png
    - assets/page-1/images/auto-group-mpmk.png
    - assets/page-1/images/image-1.png
   #images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
      - family: JosefinSans
        fonts:
          - asset: fonts/JosefinSans-Regular.ttf
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-VariableFont_wght.ttf
            weight: 600
      - family: SourceCodePro
        fonts:
          - asset: fonts/CodecPro-Regular.ttf
            weight: 600
#  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
